version: '3.8'

services:
  flask-api:
    build: .
    ports:
      - "3002:3002"
    environment:
      - DB_USERNAME=fp-finance
      - DB_PASSWORD=0000
      - DB_HOST=host.docker.internal
      - DB_PORT=5433
      - DB_NAME=fp-admin
      - NEWS_API_KEY=2c2fc7c86f0a423da4c2dd31d78cedcf
    volumes:
      - .:/app
